# Copyright (c) 2025 Joshua Hendricks Cole (DBA: Corporation of Light). All Rights Reserved. PATENT PENDING.
#
# Better Business Builder API Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-api
  namespace: bbb-production
  labels:
    app: bbb-api
    component: backend
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bbb-api
  template:
    metadata:
      labels:
        app: bbb-api
        component: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api
        image: bbb/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        # From ConfigMap
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: bbb-config
              key: APP_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: bbb-config
              key: LOG_LEVEL
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: bbb-config
              key: API_PORT

        # From Secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: DATABASE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: JWT_SECRET_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: OPENAI_API_KEY
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: SENDGRID_API_KEY
        - name: BUFFER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: BUFFER_ACCESS_TOKEN
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: bbb-secrets
              key: ENCRYPTION_KEY

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]

      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: bbb-api-service
  namespace: bbb-production
  labels:
    app: bbb-api
    component: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: bbb-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bbb-api-hpa
  namespace: bbb-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bbb-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
